// shared.js — theme toggle + site nav inject + reveal + custom cursor
(function () {
  var html = document.documentElement;
  var saved = localStorage.getItem('pp-theme');
  if (saved) html.setAttribute('data-theme', saved);
  else html.setAttribute('data-theme', 'light');

  function pageLink(hash) {
    var path = location.pathname.replace(/\/$/, '').split('/').pop() || '';
    var isHome = path === '' || path === 'index' || path === 'index.html';
    if (!hash) return '/';
    return isHome ? '#' + hash : '/#' + hash;
  }

  document.addEventListener('DOMContentLoaded', function () {
    (function ensureNav() {
      if (document.querySelector('[data-pp="site-nav"]')) return;
      var nav = document.createElement('nav'); nav.setAttribute('data-pp','site-nav'); nav.id='nav';
      nav.innerHTML='<div class="nav-inner"><a href="/" class="nav-logo">Prince <em>Prajapati</em></a><div class="nav-links"><a href="'+pageLink('about')+'">About</a><a href="'+pageLink('services')+'">Services</a><div class="nav-dropdown"><a href="'+pageLink('industries')+'" class="nav-dropbtn" data-nav="industries">Industries We Serve <span class="nav-caret">▼</span></a><div class="nav-dropdown-content"><a href="manufacturing">Manufacturing</a><a href="logistics">Logistics</a><a href="construction">Construction</a><a href="marketing">Marketing</a><a href="textile">Textile</a></div></div><div class="nav-dropdown"><a href="sip-calculator" class="nav-dropbtn" data-nav="financial-tools">Financial Tools <span class="nav-caret">▼</span></a><div class="nav-dropdown-content"><a href="sip-calculator">SIP Calculator</a><a href="loan-calculator">Loan Calculator</a><a href="ratios">Financial Ratio Analysis</a></div></div></div><div class="nav-right"><button class="tog" id="themeToggle" type="button" aria-label="Toggle light/dark mode"><span class="tog-i m">🌙</span><span class="tog-i s">☀️</span></button><a href="#contact" class="nav-cta">Book a Call</a><button class="hamburger" id="hamburger" type="button" aria-label="Toggle menu"><span></span><span></span><span></span></button></div></div>';
      var sidebar=document.createElement('div'); sidebar.className='sidebar'; sidebar.id='sidebar'; sidebar.innerHTML='<div class="sidebar-content"><div class="sidebar-header"><button class="sidebar-close" id="sidebarClose" type="button" aria-label="Close menu"></button></div><div class="sidebar-links"><a href="'+pageLink('about')+'" class="sidebar-link">About</a><a href="'+pageLink('services')+'" class="sidebar-link">Services</a><div class="sidebar-dropdown"><button class="sidebar-link sidebar-dropdown-btn" type="button">Industries We Serve</button><div class="sidebar-dropdown-content"><a href="manufacturing">Manufacturing</a><a href="logistics">Logistics</a><a href="construction">Construction</a><a href="marketing">Marketing</a><a href="textile">Textile</a></div></div><div class="sidebar-dropdown"><button class="sidebar-link sidebar-dropdown-btn" type="button">Financial Tools</button><div class="sidebar-dropdown-content"><a href="sip-calculator">SIP Calculator</a><a href="loan-calculator">Loan Calculator</a><a href="ratios">Financial Ratio Analysis</a></div></div><a href="#contact" class="sidebar-link sidebar-cta">Book a Free Consultation</a></div></div>';
      document.body.prepend(sidebar); document.body.prepend(nav); document.body.classList.add('has-site-nav'); if(document.getElementById('hero'))document.body.classList.add('has-hero');
      var themeBtn=document.getElementById('themeToggle');
      if(themeBtn)themeBtn.addEventListener('click',function(e){e.preventDefault();var next=html.getAttribute('data-theme')==='dark'?'light':'dark';html.setAttribute('data-theme',next);localStorage.setItem('pp-theme',next);updateFavicon(next);});
      function updateFavicon(theme){var prefix=theme==='dark'?'favicon-dark':'favicon-light';var a=document.getElementById('favicon-main'),b=document.getElementById('favicon-32'),c=document.getElementById('favicon-16'),d=document.getElementById('favicon-apple');if(a)a.href=prefix+'-64.png';if(b)b.href=prefix+'-32.png';if(c)c.href=prefix+'-16.png';if(d)d.href=prefix+'-128.png';}
      updateFavicon(localStorage.getItem('pp-theme')||'light'); window.addEventListener('scroll',function(){nav.classList.toggle('scrolled',window.scrollY>50);},{passive:true});
      var isCoarsePointer=window.matchMedia('(pointer:coarse)').matches,hoverCloseTimer=null;
      function closeDropdowns(){nav.querySelectorAll('.nav-dropdown.open').forEach(function(d){d.classList.remove('open');});document.body.classList.remove('nav-dropdown-open');}
      function openDropdown(d){if(d.classList.contains('open'))return;closeDropdowns();d.classList.add('open');document.body.classList.add('nav-dropdown-open');}
      nav.querySelectorAll('.nav-dropdown').forEach(function(dropdown){var btn=dropdown.querySelector('.nav-dropbtn'),content=dropdown.querySelector('.nav-dropdown-content');if(!btn||!content)return;btn.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();if(dropdown.classList.contains('open'))closeDropdowns();else openDropdown(dropdown);});if(!isCoarsePointer){dropdown.addEventListener('mouseenter',function(){clearTimeout(hoverCloseTimer);openDropdown(dropdown);});dropdown.addEventListener('mouseleave',function(){clearTimeout(hoverCloseTimer);hoverCloseTimer=setTimeout(closeDropdowns,180);});}content.querySelectorAll('a').forEach(function(link){link.addEventListener('click',closeDropdowns);});});
      document.addEventListener('click',function(e){if(!e.target.closest('.nav-dropdown'))closeDropdowns();});document.addEventListener('keydown',function(e){if(e.key==='Escape')closeDropdowns();});
      var hamburger=document.getElementById('hamburger'),sidebarClose=document.getElementById('sidebarClose');
      if(hamburger&&sidebar&&sidebarClose){function openSidebar(){hamburger.classList.add('active');sidebar.classList.add('active');document.body.classList.add('sidebar-open');}function closeSidebar(){hamburger.classList.remove('active');sidebar.classList.remove('active');document.body.classList.remove('sidebar-open');}hamburger.addEventListener('click',function(){if(sidebar.classList.contains('active'))closeSidebar();else openSidebar();});sidebarClose.addEventListener('click',closeSidebar);sidebar.querySelectorAll('.sidebar-link:not(.sidebar-dropdown-btn)').forEach(function(link){link.addEventListener('click',closeSidebar);});sidebar.querySelectorAll('.sidebar-dropdown-btn').forEach(function(btn){btn.addEventListener('click',function(){var content=btn.nextElementSibling;if(content&&content.classList.contains('sidebar-dropdown-content')){btn.classList.toggle('active');content.classList.toggle('active');}});});document.addEventListener('click',function(e){if(sidebar.classList.contains('active')&&!sidebar.contains(e.target)&&!hamburger.contains(e.target))closeSidebar();});}
    })();

    (function ensureContact(){
      var slot=document.querySelector('[data-pp="contact-slot"]');if(!slot||document.querySelector('[data-pp="contact-section"]'))return;
      var titleTpl=slot.querySelector('[data-cta-title]'),subTpl=slot.querySelector('[data-cta-sub]');
      var titleHTML=titleTpl?titleTpl.innerHTML.trim():'Ready to <mark>transform your business?</mark><br>Let\'s talk.';
      var subHTML=subTpl?subTpl.innerHTML.trim():'Whether you\'re embarking on your <strong>first ERP implementation</strong>, migrating from a legacy system, or ready to unlock <strong>AI-driven automation</strong> — we\'re here to help. No pressure, no jargon — just an <mark>honest conversation</mark> about your business.';
      var section=document.createElement('section');section.id='contact';section.setAttribute('data-pp','contact-section');
      section.innerHTML='<div class="wrap"><div class="contact-inner"><div class="eyebrow reveal" style="justify-content:center">Get In Touch</div><h2 class="contact-h2 serif reveal" style="transition-delay:.06s">'+titleHTML+'</h2><p class="sub contact-sub reveal" style="transition-delay:.12s">'+subHTML+'</p><div class="qr-cards reveal" style="transition-delay:.14s; margin-top:8px"><div class="qr-card qr-card--call"><div class="qr-card__top"><div class="qr-card__brand"><div class="qr-card__mark">PP</div><div class="qr-card__name">Prince Prajapati</div></div><div class="qr-card__meta"><span>ERP &amp; AI Consultant</span><span>Ahmedabad, IN</span></div><div class="qr-card__fields"><div><label>Response</label><div>Within 24h</div></div><div><label>Availability</label><div>Mon – Sat</div></div></div></div><div class="qr-perf"></div><div class="qr-card__bottom"><div class="qr-route"><div><div class="qr-route__code">CALL</div><div class="qr-route__sub">+91 70431 76485</div></div><div class="qr-route__icon" aria-hidden="true">📞</div></div><div class="qr-block"><div class="qr-wrap" id="qr-call"><img src="qr-call.svg" alt="QR code to call Prince Prajapati" loading="eager"></div><div class="qr-copy"><strong>Scan to dial</strong>Opens your phone\'s dialer, ready to call.</div></div><div class="qr-card__actions"><button class="qr-help" type="button" onclick="savePrinceContact()" title="Save contact">＋</button><a class="qr-wallet" href="tel:+917043176485">Call now</a></div></div></div><div class="qr-card qr-card--mail"><div class="qr-card__top"><div class="qr-card__brand"><div class="qr-card__mark">PP</div><div class="qr-card__name">Prince Prajapati</div></div><div class="qr-card__meta"><span>ERP &amp; AI Consultant</span><span>Ahmedabad, IN</span></div><div class="qr-card__fields"><div><label>Response</label><div>Within 24h</div></div><div><label>Best For</label><div>Project briefs</div></div></div></div><div class="qr-perf"></div><div class="qr-card__bottom"><div class="qr-route"><div><div class="qr-route__code">MAIL</div><div class="qr-route__sub">prince679.pro@gmail.com</div></div><div class="qr-route__icon" aria-hidden="true">✉️</div></div><div class="qr-block"><div class="qr-wrap" id="qr-mail"><img src="qr-mail.svg" alt="QR code to email Prince Prajapati" loading="eager"></div><div class="qr-copy"><strong>Scan to email</strong>Opens a message pre-addressed to Prince.</div></div><div class="qr-card__actions"><button class="qr-help" type="button" onclick="savePrinceContact()" title="Save contact">＋</button><a class="qr-wallet" href="mailto:prince679.pro@gmail.com">Email now</a></div></div></div></div></div></div>';
      slot.replaceWith(section);

      var cards=section.querySelector('.qr-cards');
      if(cards){cards.style.width='min(1080px, calc(100vw - 32px))';cards.style.marginLeft='auto';cards.style.marginRight='auto';cards.style.display='grid';cards.style.gridTemplateColumns='repeat(2, minmax(0, 1fr))';cards.style.gap='24px';}
      section.querySelectorAll('.qr-card').forEach(function(card){card.style.width='100%';card.style.minWidth='0';});

      window.savePrinceContact=window.savePrinceContact||function(){var vcard=['BEGIN:VCARD','VERSION:3.0','N:Prajapati;Prince;;;','FN:Prince Prajapati','ORG:ERP Consulting & AI Workflow Design','TITLE:ERP & AI Consultant','TEL;TYPE=CELL:+917043176485','EMAIL:prince679.pro@gmail.com','END:VCARD'].join('\n');var blob=new Blob([vcard],{type:'text/vcard'});var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prince-prajapati.vcf';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);};

      function renderContactIcons(){}
      renderContactIcons();
    })();

    (function ensureFooter(){if(document.querySelector('footer[data-pp="site-footer"]'))return;var year=new Date().getFullYear(),foot=document.createElement('footer');foot.setAttribute('data-pp','site-footer');foot.innerHTML='<div class="footer-inner"><a href="/" class="footer-logo">Prince <em>Prajapati</em></a><div class="footer-copy">© '+year+' Prince Prajapati · ERP &amp; AI Consultant · Ahmedabad, India</div><div class="footer-links"><a href="'+pageLink('about')+'">About</a><a href="'+pageLink('services')+'">Services</a><a href="#contact">Contact</a><a href="games.html" class="footer-highlight">\ud83c\udfae Brain Games</a></div></div>';document.body.appendChild(foot);})();

    /* Homepage scroll cues: down hint in hero, up hint only while Contact is visible. */
    (function ensureHomepageScrollCues(){
      if(!document.getElementById('hero') || document.querySelector('[data-pp="home-scroll-cues"]')) return;
      var style=document.createElement('style');style.id='pp-home-scroll-cue-style';style.textContent='@keyframes ppCueWheel{0%{transform:translate(-50%,0);opacity:1}65%{transform:translate(-50%,11px);opacity:0}100%{transform:translate(-50%,11px);opacity:0}}@keyframes ppCueUp{0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)}}.pp-home-scroll-cue{position:fixed;left:50%;bottom:22px;width:36px;height:48px;min-width:36px;min-height:48px;transform:translateX(-50%);z-index:400;display:flex;align-items:center;justify-content:center;cursor:pointer;opacity:.96;visibility:visible;transition:opacity .3s,transform .3s,visibility .3s;background:none;border:none;padding:0;margin:0}.pp-home-scroll-cue:hover{opacity:1}.pp-home-scroll-cue.is-hidden{opacity:0;visibility:hidden;pointer-events:none;transform:translate(-50%,8px)}.pp-home-scroll-cue.pp-down{border-radius:11px}.pp-home-scroll-cue .pp-mouse{position:relative;display:block;width:20px;height:32px;min-width:20px;min-height:32px;box-sizing:border-box;border:2px solid var(--gold-l,#d4a853);border-radius:11px;background:rgba(212,168,83,.035);box-shadow:0 0 12px rgba(212,168,83,.35),inset 0 0 7px rgba(212,168,83,.08)}.pp-home-scroll-cue.pp-up .pp-mouse{display:flex;align-items:center;justify-content:center}.pp-home-scroll-cue.pp-up svg{width:13px;height:13px;color:var(--gold-l,#d4a853);filter:drop-shadow(0 0 6px rgba(212,168,83,.7));animation:ppCueUp 1.6s ease-in-out infinite}.pp-home-scroll-cue.pp-down .pp-wheel{position:absolute;left:50%;top:5px;width:5px;height:9px;min-width:5px;min-height:9px;border-radius:5px;background:var(--gold-l,#d4a853);box-shadow:0 0 8px rgba(212,168,83,.9);transform:translateX(-50%);animation:ppCueWheel 1.7s ease-in-out infinite}@media(max-width:560px){.pp-home-scroll-cue{bottom:16px;width:34px;height:44px;min-width:34px;min-height:44px}.pp-home-scroll-cue .pp-mouse{width:18px;height:30px;min-width:18px;min-height:30px;border-radius:10px}.pp-home-scroll-cue.pp-down .pp-wheel{top:5px;width:5px;height:8px;min-width:5px;min-height:8px}}@media(prefers-reduced-motion:reduce){.pp-home-scroll-cue *{animation:none!important}.pp-home-scroll-cue{transition:none!important}}';document.head.appendChild(style);
      var down=document.createElement('div');down.setAttribute('data-pp','home-scroll-cues');down.className='pp-home-scroll-cue pp-down';down.setAttribute('role','button');down.setAttribute('aria-label','Scroll to explore');down.innerHTML='<span class="pp-mouse"><span class="pp-wheel"></span></span>';
      var up=document.createElement('div');up.className='pp-home-scroll-cue pp-up is-hidden';up.setAttribute('role','button');up.setAttribute('aria-label','Back to top');up.innerHTML='<span class="pp-mouse"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 15l-6-6-6 6"/></svg></span>';
      document.body.appendChild(down);document.body.appendChild(up);
      function goNext(){var hero=document.getElementById('hero'),target=hero&&hero.nextElementSibling;if(target)target.scrollIntoView({behavior:'smooth',block:'start'});}
      down.addEventListener('click',goNext);up.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'});});
      function update(){var y=window.scrollY||window.pageYOffset,contact=document.querySelector('[data-pp="contact-section"]'),contactVisible=false;if(contact){var r=contact.getBoundingClientRect();contactVisible=r.top<window.innerHeight*0.92&&r.bottom>window.innerHeight*0.08;}down.classList.toggle('is-hidden',y>100);up.classList.toggle('is-hidden',!contactVisible);}
      window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();
    })();

    var io=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target);}});},{threshold:.1,rootMargin:'0px 0px -40px 0px'});document.querySelectorAll('.reveal').forEach(function(el){io.observe(el);});
    var highlightObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');highlightObserver.unobserve(entry.target);}});},{threshold:.2,rootMargin:'0px 0px -10% 0px'});document.querySelectorAll('mark, .pp-highlight').forEach(function(el){highlightObserver.observe(el);});

    var isTouchDevice=window.matchMedia('(pointer:coarse)').matches;if(isTouchDevice){document.body.classList.add('touch-device');return;}
    var dot=document.getElementById('cursor-dot'),ring=document.getElementById('cursor-ring');if(!dot||!ring)return;
    var mx=-100,my=-100,rx=-100,ry=-100;document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});document.addEventListener('mousedown',function(){ring.classList.add('clicking');});document.addEventListener('mouseup',function(){ring.classList.remove('clicking');});
    var hoverEls='a, button, .calc-btn, .prod-tab, .ratio-input-method, .svc, .ind-card, .ccard, .btn-gold, .trust-chip, .flow-step, .nav-cta, .tog, .hamburger, .nav-links a, .qr-wallet, .qr-help, .qr-card, .footer-links a';document.querySelectorAll(hoverEls).forEach(function(el){el.addEventListener('mouseenter',function(){ring.classList.add('hovering');});el.addEventListener('mouseleave',function(){ring.classList.remove('hovering');});});
    function lerp(a,b,t){return a+(b-a)*t;}function loop(){dot.style.left=mx+'px';dot.style.top=my+'px';rx=lerp(rx,mx,.12);ry=lerp(ry,my,.12);ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(loop);}loop();document.addEventListener('mouseleave',function(){dot.style.opacity=0;ring.style.opacity=0;});document.addEventListener('mouseenter',function(){dot.style.opacity=1;ring.style.opacity='';});
  });
})();
